# yamllint disable rule:truthy
---
name: OpenSSF Scorecard

on:
  schedule:
    - cron: "23 4 * * 2"
  workflow_dispatch:
  branch_protection_rule:
  push:
    branches: ["main"]

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  scorecard:
    name: OpenSSF Scorecard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@v2.4.2
        with:
          results_file: scorecard.sarif
          results_format: sarif
          publish_results: true

      - name: Upload Scorecard SARIF
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: scorecard.sarif
